{
	"name": "test_fail_activity_logging",
	"properties": {
		"activities": [
			{
				"name": "Name",
				"description": "Description",
				"type": "Fail",
				"dependsOn": [],
				"userProperties": [],
				"typeProperties": {
					"message": "This has failed",
					"errorCode": "42"
				}
			},
			{
				"name": "Notebook1",
				"type": "SynapseNotebook",
				"dependsOn": [
					{
						"activity": "Name",
						"dependencyConditions": [
							"Completed"
						]
					}
				],
				"policy": {
					"timeout": "0.12:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"notebook": {
						"referenceName": "py_fail_logging",
						"type": "NotebookReference"
					},
					"parameters": {
						"output": {
							"value": {
								"value": "@activity('Name').output.message",
								"type": "Expression"
							},
							"type": "string"
						}
					},
					"snapshot": true
				}
			}
		],
		"annotations": []
	}
}